### ISSUE TITLE
$docker->containerCreate() returns null without errors

### ISSUE THREAD

**Issue by binsky08** [beluga-php/docker-php#56] opened 2023-10-17 16:20 UTC
When using the current docker-php main branch, together with the current docker-php-api master, I have the problem that
`$docker->containerCreate($containerConfig);` returns null, but without any exception. The requested container was not created.

System:
- Debian 12
- Docker version 24.0.6
- php8.2

Code snippet with a simplified version of the usage:
```php
$docker = Docker::create();
$containerConfig = new ContainersCreatePostBody();
$containerConfig->setImage($docker_image);

$hostConfig = new HostConfig();

$portBinding = [
  'HostIp' => env('CTF_DOCKER_HOST_BIND_IP', '0.0.0.0'),
  'HostPort' => '8000'
];
$portMap[$intern . '/tcp'] = [$portBinding];
$hostConfig->setPortBindings($portMap);

$exposedPorts = [];
foreach ($portMap as $key => $value) {
    $exposedPorts[$key] = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
}
$containerConfig->setExposedPorts($exposedPorts);

$containerConfig->setHostConfig($hostConfig);

$containerCreateResult = $docker->containerCreate($containerConfig);
asserNull($containerCreateResult); // true
```

Any idea what's going wrong?

**Comment by flavioheleno** [comment] 2023-10-17 17:03
hey @binsky08, I executed something quite similar to your code (filling in some of the gaps that are left on your snippet, such as `$docker_image` and `$intern`) and got a response, look below.

```php
var_dump($containerCreateResult);
object(Docker\API\Model\ContainerCreateResponse)#33 (4) {
  ["initialized":protected]=>
  array(2) {
    ["id"]=>
    bool(true)
    ["warnings"]=>
    bool(true)
  }
  ["id":protected]=>
  string(64) "e92063f2817ded29cf939bbff02698382faff61a3bbcbe911ee33132c4487e10"
  ["warnings":protected]=>
  array(0) {
  }
  ["storage":"ArrayObject":private]=>
  array(0) {
  }
}
```

I've set `$docker_image` to `alpine:latest` and `$intern` to `80`.

**Comment by Rid** [comment] 2023-10-18 07:16
This is probably related to https://github.com/beluga-php/docker-php/issues/57

**Comment by binsky08** [comment] 2023-10-18 11:39
Thanks for the hint, you were right, is was an issue with using the docker unix socket.
I worked around it by just using a tcp socket as described here: https://docs.docker.com/config/daemon/remote-access/
So that's how its working now:
```php
$client = DockerClientFactory::create([
    'remote_socket' => 'http://127.0.0.1:2375',
]);
$docker = Docker::create($client);
...
```

**Comment by Rid** [comment] 2023-10-18 11:46
@binsky08 can you do a composer update? It should be fixed now.

**Comment by binsky08** [comment] 2023-10-18 12:39
now i'm getting `local.ERROR: bad parameter {"exception":"[object] (Docker\\API\\Exception\\ContainerCreateBadRequestException(code: 400): bad parameter` at ... /vendor/beluga-php/docker-php-api/src/Endpoint/ContainerCreate.php:96)

**Comment by binsky08** [comment] 2023-10-18 12:43
I will just use my described solution with the previous docker-php version, I pinned in a private repo, together with the current main branch commit of docker-php-api

**Comment by Rid** [comment] 2023-10-18 13:50
@binsky08 Do you mind posting the relevant parts of your `composer.json`?

**Comment by Rid** [comment] 2023-10-18 14:50
I've added better error reporting now. If you try the library again with the latest version, it will tell you what the issue is.

**Closed** 2023-10-22 22:39 UTC
